export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  VENDOR: 'VENDOR',
  STAFF: 'STAFF',
  CUSTOMER: 'CUSTOMER'
};

export const ROLE_HIERARCHY = {
  [ROLES.ADMIN]: [ROLES.MANAGER, ROLES.VENDOR, ROLES.STAFF, ROLES.CUSTOMER],
  [ROLES.MANAGER]: [ROLES.STAFF, ROLES.CUSTOMER],
  [ROLES.VENDOR]: [ROLES.CUSTOMER],
  [ROLES.STAFF]: [ROLES.CUSTOMER],
  [ROLES.CUSTOMER]: []
};

export const PERMISSIONS = {
  // User management
  CREATE_USER: 'CREATE_USER',
  READ_USER: 'READ_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  
  // Product management
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  READ_PRODUCT: 'READ_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  
  // Order management
  CREATE_ORDER: 'CREATE_ORDER',
  READ_ORDER: 'READ_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',
  
  // Inventory management
  UPDATE_INVENTORY: 'UPDATE_INVENTORY',
  READ_INVENTORY: 'READ_INVENTORY',
  
  // System settings
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS'
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.MANAGER]: [
    PERMISSIONS.READ_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.READ_PRODUCT,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.READ_ORDER,
    PERMISSIONS.UPDATE_ORDER,
    PERMISSIONS.UPDATE_INVENTORY,
    PERMISSIONS.READ_INVENTORY,
    PERMISSIONS.VIEW_ANALYTICS
  ],
  [ROLES.VENDOR]: [
    PERMISSIONS.CREATE_PRODUCT,
    PERMISSIONS.READ_PRODUCT,
    PERMISSIONS.UPDATE_PRODUCT,
    PERMISSIONS.DELETE_PRODUCT,
    PERMISSIONS.READ_ORDER,
    PERMISSIONS.UPDATE_ORDER,
    PERMISSIONS.UPDATE_INVENTORY,
    PERMISSIONS.READ_INVENTORY
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.READ_PRODUCT,
    PERMISSIONS.READ_ORDER,
    PERMISSIONS.UPDATE_ORDER,
    PERMISSIONS.READ_INVENTORY
  ],
  [ROLES.CUSTOMER]: [
    PERMISSIONS.READ_PRODUCT,
    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.READ_ORDER,
    PERMISSIONS.CANCEL_ORDER
  ]
};